on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: jaxvanyang/docker-action@main
        with:
          who-to-greet: 'Jax Van Yang'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  write_good_job:
    runs-on: ubuntu-latest
    name: A job to lint Markdown files
    steps:
      - uses: actions/checkout@v3
      - name: write-good action step
        id: write-good
        uses: tomwhross/write-good-action@v1.5
      - name: Get the write-good output
        uses: mshick/add-pr-comment@v1
